# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'ASoC'
    applications: '2d0ee5f3-cd31-4c5a-bdf4-1b84413fc887'
    scanname: 'Test ADO'
    scantype: 'static'
    scanMethod: 'IRX'
    FailBuildConfiguration: true
    FailBuildChoice: 'conditionset'
    buildfailHigh: true
    buildfailconditionHigh: '1'